- name: Check if openemr user exists
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    login_user: root
    login_unix_socket: "{{ mariadb_login_unix_socket }}"
  register: openemr_user_info
  failed_when: false
  changed_when: false

- name: Create openemr user and grant privileges
  community.mysql.mysql_user:
    login_user: root
    login_unix_socket: "{{ mariadb_login_unix_socket }}"
    name: "{{ db_user }}"
    host: "{{ emr_host }}"
    state: present
    #priv: "{{db_name}}.*:ALL" TODO expand the variable.
    priv: "*.*:ALL"

- name: Grant same privileges to root user for openemr database
  community.mysql.mysql_user:
    name: root
    password: "{{ db_root_password }}"
    host: "{{ emr_host }}"
    priv: "*.*:ALL"
    state: present
    login_unix_socket: "{{ mariadb_login_unix_socket }}"
