
- name: Ensure root@localhost uses unix_socket authentication
  community.mysql.mysql_user:
    name: root
    host: localhost
    login_unix_socket: "{{ mariadb_login_unix_socket }}"
    state: present
