- name: Install packages for OpenEMR
  become: true
  ansible.builtin.apt:
    name:
      - git
      - composer
      - build-essential
      - python3
      - make
      - g++
      - libxml2-dev
    state: present
    update_cache: yes

- name: Check if OpenEMR is already cloned
  stat:
    path: "{{ openemr_web_root }}/.git"
  register: openemr_git_repo

- name: Clone OpenEMR repository
  git:
    repo: "{{ openemr_repo_url }}"
    dest: "{{ openemr_web_root }}"
    version: "{{ openemr_branch }}"
    force: yes
  when: not openemr_git_repo.stat.exists
  notify: Set permissions


- name: Run composer install
  command: composer install --no-dev
  args:
    chdir: "{{ openemr_web_root }}"
  environment:
    COMPOSER_ALLOW_SUPERUSER: "1"

- name: Copy example .env file if .env doesn't exist
  copy:
    src: "{{ openemr_web_root }}/.env.example"
    dest: "{{ openemr_web_root }}/.env"
    remote_src: yes
  when: not lookup('file', openemr_web_root + '/.env', errors='ignore')

- name: Set ownership of OpenEMR files
  file:
    path: "{{ openemr_web_root }}"
    owner: www-data
    group: www-data
    recurse: yes

- name: Set file permissions for sites directory
  file:
    path: "{{ openemr_web_root }}/sites"
    mode: "0750"
    state: directory
    recurse: yes

- name: Set correct permissions for OpenEMR directories
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
    mode: '0755'
  loop:
    - /var/www/html/openemr/ccdaservice
    - /var/www/html/openemr/sites
    - /var/www/html/openemr/sites/default/documents
    - /var/www/html/openemr/sites/default/edi
    - /var/www/html/openemr/sites/default/era
    - /var/www/html/openemr/sites/default/letter_templates

- name: Install frontend dependencies
  command: npm install
  args:
    chdir: /var/www/html/openemr

- name: Add openemradmin user to www-data group
  become: true
  ansible.builtin.user:
    name: openemradmin
    groups: www-data
    append: yes

- name: Build frontend
  command: npm run build
  args:
    chdir: /var/www/html/openemr

# refer /var/www/html/openemr/ccdaservice/README.md
- name: Install ccda dependencies
  command: npm install
  args:
    chdir: /var/www/html/openemr/ccdaservice

- name: Set correct permissions for OpenEMR Config
  file:
    path: "{{ item }}"
    state: file
    owner: www-data
    group: www-data
    mode: '0644'
  loop:
    - /var/www/html/openemr/sites/default/sqlconf.php

- name: Copy InstallerAuto.php
  template:
    src: InstallerAuto.php.j2
    dest: /var/www/html/openemr/sites/default/InstallerAuto.php
    owner: www-data
    group: www-data
    mode: '0644'

- name: Run OpenEMR auto-installer
  command: >
    php sites/default/InstallerAuto.php
  args:
    chdir: /var/www/html/openemr
  register: openemr_install_result
  changed_when: "'Successful' in openemr_install_result.stdout"

- name: Debug OpenEMR installation output
  debug:
    var: openemr_install_result.stdout
