- name: Install MariaDB on Ubuntu
  hosts: mariadb
  become: yes
  tasks:
    - name: Update APT
      apt:
        update_cache: yes

    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present

    - name: Ensure MariaDB is running
      service:
        name: mariadb
        state: started
        enabled: yes
