- name: Install NGINX and Certbot
  apt:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
    update_cache: yes

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent


- name: Deploy PHP-FPM pool for nginx user access
  template:
    src: nginx-compatible.conf.j2
    dest: "/etc/php/8.3/fpm/pool.d/www.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Restart PHP 8.3 FPM

- name: Deploy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Reload nginx

- name: Deploy OpenEMR nginx config
  template:
    src: openemr.conf.j2
    dest: /etc/nginx/sites-available/openemr

- name: Enable OpenEMR site
  file:
    src: /etc/nginx/sites-available/openemr
    dest: /etc/nginx/sites-enabled/openemr
    state: link
  notify: Reload nginx

- name: Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Start and enable PHP
  service:
    name: php8.3-fpm
    state: started
    enabled: true

- name: Place HTTP-01 challenge file
  community.crypto.acme_certificate:
    account_key_src: "/etc/ssl/private/{{ domain_name }}-account.key"
    csr: "/etc/ssl/private/{{ domain_name }}.csr"
    dest: "/etc/ssl/certs/{{ domain_name }}.crt"
    fullchain_dest: "/etc/ssl/certs/{{ domain_name }}-fullchain.crt"
    challenge: http-01
    acme_directory: "https://acme-v02.api.letsencrypt.org/directory"
    webroot: "{{ webroot_path }}"
    remaining_days: 30
  register: acme_cert_result
  when: domain_name is defined

- name: Reload nginx if certificate changed
  ansible.builtin.service:
    name: nginx
    state: reloaded
  when: acme_cert_result.changed
